orm
jansool/myproject pull request #5
Opened 2023-04-30 19:33 UTC by jansool

2023-05-01 21:16 UTC, PonomaryovVladyslav requested changes

2023-05-01 21:16 UTC, PonomaryovVladyslav commented on myapp/views.py
> +        posts_info.append({
Так это что и зачем?)) перебрать все посты, везде сделать шорт десткрипшен, и взять часть топиков?)) я искренне не понимаю зачем это?)) вместо нормального кверисета заново пересобирать все объекты в список, зачем??

Хочется сделать шорт дескрипшен, ну сделай его как проперти, и в шаблоне используй

Такая же ситуация с обрезанными топиками, хотя я хз зачем их обрезать, но если хочется, сделай кастомный менеджер в который добавь себе метод first_three() и вызывай его в шаблоне, перебирать все то зачем?

2023-05-01 21:16 UTC, PonomaryovVladyslav commented on myapp/views.py
> +    for post in posts:
Чем эта функция отличается от blogs? тоже самое, и тоже все плохо

2023-05-01 21:16 UTC, PonomaryovVladyslav commented on myapp/views.py
> +    user_info = {
Это зачем добавлять? все эти данные и так есть в самом юзере, доставать их отдельно нет никакого смысла. А давать пользователям возможность смотреть данные других пользователей без каких либо проверок, это и так не правильно. Или делаем проверку, что эту страницу смотрит например админ или сам пользователь, или вообще убираем юзернейм и смотрим только свои данные, а они и так уже есть в реквесте

2023-05-01 21:16 UTC, PonomaryovVladyslav commented on mysite/urls.py
>      path("/update/", v.update),
Своеобразный импортинг, работать то будет, но зачем? или отдельно все импортировать надо, что было бы правильнее или поясни мне зачем тут переименовывание views

2023-05-02 09:48 UTC, jansool commented on myapp/views.py
> +        posts_info.append({
Это из задания: список пов’язаних тем (перші 3 теми або менше)
обрізаний вміст (~50 слів або менше)
кількість коментарів

Реализацию исправлю

2023-05-02 09:52 UTC, jansool commented on myapp/views.py
> +    for post in posts:
Да, это я не подумала

2023-05-02 09:59 UTC, jansool commented on mysite/urls.py
>      path("/update/", v.update),
Не знаю, подумала что мне так будет читабельнее

2023-05-02 11:12 UTC, PonomaryovVladyslav approved these changes

2023-05-03 16:34 UTC, merged